version: "3.0"  # orig 3.0
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: perfectfit
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  manage_db:
    build: https://github.com/PerfectFit-project/virtual-coach-db.git#main
    tty: true
    restart: on-failure
    command: ["/app/utils/init-db-tests.sh"]
    env_file:
      - .env

  rasa_server:
    build:
      context: https://github.com/PerfectFit-project/virtual-coach-rasa.git#main:Rasa_Bot
    ports:
      - 5005:5005
    expose: ["5005"]
    env_file:
      - .env

  rasa_actions:
    build:
      context: https://github.com/PerfectFit-project/virtual-coach-rasa.git#main:Rasa_Bot/actions
    expose: ["5055"]
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379

  scheduler:
    build:
      context: https://github.com/PerfectFit-project/virtual-coach-rasa.git#main:scheduler
    depends_on:
     - redis
     - rasa_server
    env_file:
      - .env

# Niceday components depend on 'goalie-js', which is a private repository.
# Thus, we cannot directly build it from github, so we build it from the cloned repository.
  niceday_broker:
    build:
      context: ./build/niceday-components/niceday-broker
    env_file:
      - .env

  niceday_api:
    build:
      context: ./build/niceday-components/niceday-api
    env_file:
      - .env
    ports:
      - 8080:8080
    expose: ["8080"]
