version: "3.0"  # orig 3.0
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: perfectfit
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d perfectfit"]
      interval: 5m
      timeout: 5m
      retries: 5
    volumes:
      - ./init_db_scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  manage_db:
    build: https://github.com/PerfectFit-project/virtual-coach-db.git#main
    tty: true
    depends_on:
      - db

  rasa_server:
    build: https://github.com/PerfectFit-project/virtual-coach-rasa.git#main:Rasa_Bot
    ports:
      - 5005:5005
    expose: ["5005"]

  rasa_actions:
    build: https://github.com/PerfectFit-project/virtual-coach-rasa.git#main:Rasa_Bot/actions
    expose: ["5055"]
    env_file:
      - .env
    environment:
      DB_HOST: db:5432

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379

  scheduler:
    build: https://github.com/PerfectFit-project/virtual-coach-rasa.git#main:scheduler
    depends_on:
     - redis
     - rasa_server
    environment:
      DB_HOST: db:5432

# Niceday components depend on 'goalie-js', which is a private repository.
# Thus, we cannot directly build it from github, so we build it from the cloned repository.
  niceday_broker:
    build: ./build/niceday-components/niceday-broker
    env_file:
      - .env

  niceday_api:
    build: ./build/niceday-components/niceday-api
    env_file:
      - .env
