version: "3.0"  # orig 3.0
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: perfectfit
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d perfectfit"]
      interval: 5m
      timeout: 5m
      retries: 5
    volumes:
      - ./init_db_scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  manage_db:
    image: manage-db
    build: .
    tty: true
    depends_on:
      - db

  rasa_server:
    image: rasa-server
    ports:
      - 5005:5005
    expose: ["5005"]

  rasa_actions:
    image: rasa-actions
    expose: ["5055"]
    env_file:
      - .env
    environment:
      DB_HOST: db:5432

  niceday_broker:
    image: niceday-broker
    env_file:
      - .env

  niceday_api:
    image: niceday-api
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379

  scheduler:
    image: scheduler
    depends_on:
     - redis
     - rasa_server
    environment:
      DB_HOST: db:5432
