---
- name: Update staging server
  hosts: stage
  user: root
  tasks:
    - name: Copy .env for staging
      ansible.builtin.copy:
        src: ../.env.stage
        dest: ~/.env.stage
        mode: '0644'
    - name: Copy private package token
      ansible.builtin.copy:
        src: ../SECRET_read_private_packages_token
        dest: ~/SECRET_read_private_packages_token
        mode: '0644'
    - name: Copy private sensor token
      ansible.builtin.copy:
        src: ../id_rsa_perfectfitsensor
        dest: ~/id_rsa_perfectfitsensor
        mode: '0644'
    - name: Copy docker compose staging yml
      ansible.builtin.copy:
        src: ../stage/docker-compose.stage.yml
        dest: ~/docker-compose.stage.yml
        mode: '0644'
    - name: Log into docker ghcr
      shell: cat SECRET_read_private_packages_token | docker login ghcr.io -u USERNAME --password-stdin
    - name: Stop docker compose (if up)
      shell: 'docker compose -f docker-compose.stage.yml down --remove-orphans --rmi all -v'
    - name: Stop any containers that may have been missed by the "docker compose down"
      shell: 'docker stop $(docker container ls -q)'
      ignore_errors: true
    - name: Prune containers and networks
      shell: 'docker system prune -a --volumes -f'
    - name: Start docker compose
      shell: 'docker compose -f docker-compose.stage.yml up -d'
