version: "3.0"  # orig 3.0
services:
  db:
    image: postgres
    expose: ["5432"]
    restart: always
    environment:
      POSTGRES_DB: perfectfit
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  manage_db:
    build: https://github.com/PerfectFit-project/virtual-coach-db.git#main
    tty: true
    restart: on-failure
    command: ["/app/utils/init-db.sh"]
    env_file:
      - .env.stage

  rasa_server:
    image: ghcr.io/perfectfit-project/rasa_server:latest
    expose: ["5005"]

  rasa_actions:
    image: ghcr.io/perfectfit-project/rasa_actions:latest
    expose: ["5055"]
    env_file:
      - .env.stage

  redis:
    image: "redis:alpine"
    expose: ["6379"]

  scheduler:
    image: ghcr.io/perfectfit-project/scheduler:latest
    expose: ["8080"]
    depends_on:
     - redis
     - rasa_server
    env_file:
      - .env.stage

  niceday_broker:
    image: ghcr.io/perfectfit-project/niceday_broker:latest
    env_file:
      - .env.stage

  niceday_api:
    image: ghcr.io/perfectfit-project/niceday_api:latest
    env_file:
      - .env.stage
